// Generated by CoffeeScript 1.7.1
(function() {
  test("test simple", function() {
    var appInstance, result;
    appInstance = new App;
    result = appInstance.f("testName", function() {});
    return ok(true);
  });

}).call(this);

//# sourceMappingURL=app.test.map
