// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  App = require("../../src/app");

  module.exports.AppTest = {
    "test listener gear": function(test) {
      var appInstance, isTestPassed, listener;
      appInstance = new App();
      listener = appInstance.scope.createListener();
      isTestPassed = true;
      listener.subscribe("test", function(param) {
        return isTestPassed = param;
      });
      listener.trigger("test", true);
      test.ok(isTestPassed);
      return test.done();
    }
  };

}).call(this);
