// Generated by CoffeeScript 1.7.1
(function() {
  var App, Listener, Load, Queue, Response, Scope;

  App = (function() {
    function App(window, $, _) {
      this.window = window;
      this.$ = $;
      this._ = _;
      this.viewFunctions = {};
      if (this.scope == null) {
        this.scope = new Scope();
      }
    }

    App.prototype.f = function(name, func) {
      return this.viewFunctions[name] = func;
    };

    App.prototype.apply = function() {};

    return App;

  })();

  Response = (function() {
    function Response(params) {
      this.params = params;
    }

    Response.prototype.bindApply = function(callback) {};

    Response.prototype.apply = function() {};

    return Response;

  })();

  Scope = (function() {
    function Scope() {}

    Scope.prototype.createListener = function() {
      return new Listener();
    };

    return Scope;

  })();

  Listener = (function() {
    var subscribers;

    function Listener() {}

    subscribers = {};

    Listener.prototype.trigger = function(name, params) {
      return subscribers[name].reduce(function(f) {
        return f(params);
      });
    };

    Listener.prototype.subscribe = function(name, callback) {
      if (subscribers[name] == null) {
        subscribers[name] = [];
      }
      subscribers[name].push(callback);
      return this;
    };

    return Listener;

  })();

  Load = (function() {
    function Load() {}

    return Load;

  })();

  Queue = (function() {
    function Queue() {}

    return Queue;

  })();

  if (module && module.exports) {
    module.exports = App;
  }

}).call(this);
