// Generated by CoffeeScript 1.7.1
(function() {
  var App, Listener, Load, Queue, Response, Scope;

  App = (function() {
    function App(window, $, _) {
      this.window = window;
      this.$ = $;
      this._ = _;
      this.viewFunctions = {};
    }

    App.prototype.f = function(name, func) {
      return this.viewFunctions[name] = func;
    };

    App.prototype.apply = function() {};

    return App;

  })();

  Response = (function() {
    function Response(params) {
      this.params = params;
    }

    Response.prototype.bindApply = function(callback) {};

    Response.prototype.apply = function() {};

    return Response;

  })();

  Scope = (function() {
    function Scope() {}

    return Scope;

  })();

  Listener = (function() {
    function Listener() {}

    return Listener;

  })();

  Load = (function() {
    function Load() {}

    return Load;

  })();

  Queue = (function() {
    function Queue() {}

    return Queue;

  })();

  if (module && module.exports) {
    module.exports = App;
  }

}).call(this);
