// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  App = require("../../src/app");

  module.exports.AppTest = {
    setUp: function(callback) {
      this.appInstance = new App;
      return callback();
    },
    "test simple": function(test) {
      var result;
      result = this.appInstance.f("testName", function() {});
      test.equal(result, true);
      return test.done;
    }
  };

}).call(this);
