// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  App = require("../../src/app");

  module.exports.AppTest = {
    "test simple": function(test) {
      var appInstance, result;
      appInstance = new App();
      result = appInstance.f("testName", function() {});
      test.equal(true, true);
      return test.done();
    }
  };

}).call(this);
